try {
    let x = 2
} catch (error) {
    console.error(error)
}